trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs: 
      versionSpec: '3.10'
  
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      pip install pytest
    displayName: 'Install pytest'

  - script: |
      echo $(pwd)
      PYTHONPATH=$(pwd) pytest
    displayName: 'Run tests'